name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Trigger deployment on pushes to the main branch

  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies and build project
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages # Deployment branch
          folder: dist # Folder containing compiled files
